version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-soporte
    restart: always
    environment:
      POSTGRES_DB: soportedb
      POSTGRES_USER: soporte
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spring-soporte
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/soportedb
      SPRING_DATASOURCE_USERNAME: soporte
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  pgdata:
